#!/bin/bash
# git-create-branch [remote_name] branch_name
# Creates the branch_name branch on the origin, then creates a local tracking branch
# Thanks: http://www.zorched.net/2008/04/14/start-a-new-branch-on-your-remote-git-repository/
# @author Weston Ruter (@westonruter), X-Team

set -e

if [ $# == 2 ]; then
    remote_name=$1
    branch_name=$2
elif [ $# == 1 ]; then
    remote_name="origin"
    branch_name=$1
else
    echo 1>&2 Usage: $0 branch_name
    exit 127
fi

git push ${remote_name} ${remote_name}:refs/heads/${branch_name}
git fetch ${remote_name}
git checkout --track -b ${branch_name} ${remote_name}/${branch_name}
git pull
